### ISSUE TITLE
Error: Missing `oauth_callback_confirmed` parameter in response

### ISSUE THREAD

**Issue by mokszekei** [feross/login-with-twitter#11]
when I follow the example codes, I got error:
Error: Missing `oauth_callback_confirmed` parameter in response
req.session.tokenSecret = tokenSecret
                            ^

TypeError: Cannot set property 'tokenSecret' of undefined
Why is this?

**Comment by feross** [comment]
You need to ensure you have a `session` property on your request object which comes from using an express middleware that handles sessions.

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Comment by mokszekei** [comment]
Thanks for your reply. I already set up session property with app.use(session()). Session doesn’t seem like the problem. The “tokenSecret”parameter in tw.login(err,tokenSecret,url) call back function is undefined. Seems like authentication is declined?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by feross** [comment]
Your error indicates that `req.session` is undefined. Anyway, this is not a support forum.
