### ISSUE TITLE
'https://api.twitter.com/oauth/request_token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### ISSUE THREAD

**Issue by jxnx888** [feross/login-with-twitter#14]
'https://api.twitter.com/oauth/request_token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ashwwwin** [comment]
Did you end up finding a fix for this?

**Comment by jxnx888** [comment]
> Did you end up finding a fix for this?

Finally, I did not use this plugin, I am using `hellojs` (hellojs('twitter')) to fetch the token
