### ISSUE TITLE
The callback only returns fixed 4 params, can it return everything?

### ISSUE THREAD

**Issue by yusufnb** [feross/login-with-twitter#6]
For example, if we have enable email_id, that data does not return via the callback method.

Thanks

**Comment by aryankanwar** [comment]
The response comes from twitter's POST oauth/access_token API
https://developer.twitter.com/en/docs/authentication/api-reference/access_token

 which returns 
```
Example response
oauth_token=6253282-eWudHldSbIaelX7swmsiHImEL4KinwaGloHANdrY&oauth_token_secret=2EEfA6BG5ly3sR3XjE0IBSnlQu4ZrUzPiYTmrkVU&user_id=6253282&screen_name=twitterapi
```

So If you want to fetch extra information you can make a request to Twitter user details fetch API inside twitter callback GET API of yours.
