### ISSUE TITLE
Want the solution for frontend Vuejs

### ISSUE THREAD

**Issue by sunnykanakhara** [feross/login-with-twitter#9]
Hello, you have used backend as nodejs in your repository but i want the only vuejs solution to get the user oauth token from front side  and then forward it to backend laravel, can you please provide me solution to authenticate user from frontside in vuejs with the source code or any other reference from your side.

**Comment by feross** [comment]
Sorry that's not what this repo does.

**Comment by sunnykanakhara** [comment]
Can you please help me out as a sample code to authenticate and login user in twittr from frontend in vuejs  ?
